name: Coverage

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        # default fetch-depth is insufficent to find previous coverage notes
        fetch-depth: 10

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        coverage-threshold: 80
        fail-coverage: never

        cover-pkg: ./...
