name: Release

on:
  release:
    types:
    - published

env:
  IMAGE_SERVER: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build

    - name: Test
      run: go test ./...

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: |
        CGO_ENABLED=0 go build -ldflags '-s -w'

    - uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_SERVER }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
